.PHONY: all check test unstow _check-prereqs _build-codex

PKGS := fish alacritty zed git cloc lazygit mise ai-shared claude codex opencode
TARGET ?= $(HOME)
TARGET_ABS := $(abspath $(TARGET))
STOW ?= stow
MEMORIES := ai-shared/.ai/memories
STOW_FLAGS := --no-folding

all: _build-codex
	@bash scripts/manage-conflicts.sh backup "$(TARGET_ABS)" $(PKGS)
	$(STOW) $(STOW_FLAGS) -R -t "$(TARGET_ABS)" $(PKGS)
	@bash scripts/manage-claude-skills.sh link "$(TARGET_ABS)"
	@bash scripts/install-kickstart.sh "$(TARGET_ABS)"
	@bash scripts/install-fisher.sh "$(TARGET_ABS)"

check: _check-prereqs
	@bash scripts/manage-conflicts.sh check "$(TARGET_ABS)" $(PKGS)
	$(STOW) $(STOW_FLAGS) --simulate -t "$(TARGET_ABS)" $(PKGS)

test:
	@bash tests/test-deploy.sh

unstow:
	@command -v "$(STOW)" >/dev/null 2>&1 || { echo "Missing required command: $(STOW)" >&2; exit 1; }
	@bash scripts/manage-claude-skills.sh unlink "$(TARGET_ABS)"
	$(STOW) $(STOW_FLAGS) -t "$(TARGET_ABS)" -D $(PKGS)

_check-prereqs:
	@bash scripts/check-prereqs.sh

# Codex has no import mechanism, so merge the tracked common block into its live config.
_build-codex: _check-prereqs
	@mkdir -p codex/.codex
	@printf '%s\n' \
		'<!-- GENERATED by `make` from ~/.ai/memories/*.md. Do not edit. -->' \
		'' > codex/.codex/AGENTS.md
	@for f in $(MEMORIES)/*.md; do \
		cat "$$f" >> codex/.codex/AGENTS.md; \
		printf '\n' >> codex/.codex/AGENTS.md; \
	done
	@echo "Generated codex/.codex/AGENTS.md from $$(ls $(MEMORIES)/*.md | wc -l) memory files"
	@python3 scripts/merge-codex-config.py \
		codex-managed.toml \
		"$(TARGET_ABS)/.codex/config.toml"
	@echo "Merged shared settings into $(TARGET_ABS)/.codex/config.toml"
