.PHONY: check stow unstow restow ai ai-check ai-unstow ai-prereqs build-codex link-claude-skills

PKGS := fish alacritty zed
AI_PKGS := ai-shared claude codex opencode
TARGET ?= $(HOME)
STOW ?= stow
MEMORIES := ai-shared/.ai/memories

check:
	$(STOW) --simulate -t "$(TARGET)" $(PKGS)

stow:
	$(STOW) -t "$(TARGET)" $(PKGS)

unstow:
	$(STOW) -t "$(TARGET)" -D $(PKGS)

restow:
	$(STOW) -t "$(TARGET)" -R $(PKGS)

# Remove files that would conflict with stow before linking AI packages.
# opencode.jsonc is replaced by the dotfiles version.
ai-prereqs:
	@rm -f "$(TARGET)/.config/opencode/opencode.jsonc"
	@rm -rf "$(TARGET)/.claude/skills"

# Claude reads ~/.claude/skills; point it at ~/.agents/skills (already stowed from ai-shared).
link-claude-skills:
	@ln -sfn "$(TARGET)/.agents/skills" "$(TARGET)/.claude/skills"

# Codex has no import mechanism, so its AGENTS.md must be a single file.
# Generate it from the shared memories instead of hand-maintaining a copy.
# The output is gitignored — edit files in $(MEMORIES) instead.
build-codex:
	@mkdir -p codex/.codex
	@printf '%s\n' \
		'<!-- GENERATED by `make build-codex` from ~/.ai/memories/*.md. Do not edit. -->' \
		'' > codex/.codex/AGENTS.md
	@for f in $(MEMORIES)/*.md; do \
		cat "$$f" >> codex/.codex/AGENTS.md; \
		printf '\n' >> codex/.codex/AGENTS.md; \
	done
	@echo "Generated codex/.codex/AGENTS.md from $$(ls $(MEMORIES)/*.md | wc -l) memory files"

ai: ai-prereqs build-codex
	$(STOW) -t "$(TARGET)" $(AI_PKGS)
	$(MAKE) link-claude-skills

ai-check:
	$(STOW) --simulate -t "$(TARGET)" $(AI_PKGS)

ai-unstow:
	$(STOW) -t "$(TARGET)" -D $(AI_PKGS)
