.PHONY: all check unstow

PKGS     := fish alacritty zed git cloc
AI_PKGS  := ai-shared claude codex opencode
TARGET   ?= $(HOME)
STOW     ?= stow
MEMORIES := ai-shared/.ai/memories

all: _prereqs _build-codex
	$(STOW) -R -t "$(TARGET)" $(PKGS) $(AI_PKGS)
	@$(MAKE) -s _link-claude-skills

check:
	$(STOW) --simulate -t "$(TARGET)" $(PKGS) $(AI_PKGS)

unstow:
	$(STOW) -t "$(TARGET)" -D $(PKGS) $(AI_PKGS)

# Remove files that conflict with stow before linking.
_prereqs:
	@rm -f "$(TARGET)/.gitconfig"
	@rm -f "$(TARGET)/.config/git/ignore"
	@rm -f "$(TARGET)/.config/opencode/opencode.jsonc"
	@rm -f "$(TARGET)/.claude/settings.json"
	@rm -rf "$(TARGET)/.claude/skills"

# Claude reads ~/.claude/skills; point it at ~/.agents/skills (already stowed from ai-shared).
_link-claude-skills:
	@ln -sfn "$(TARGET)/.agents/skills" "$(TARGET)/.claude/skills"

# Codex has no import mechanism — generate a single AGENTS.md from shared memories.
# The output is gitignored; edit files in $(MEMORIES) instead.
_build-codex:
	@mkdir -p codex/.codex
	@printf '%s\n' \
		'<!-- GENERATED by `make` from ~/.ai/memories/*.md. Do not edit. -->' \
		'' > codex/.codex/AGENTS.md
	@for f in $(MEMORIES)/*.md; do \
		cat "$$f" >> codex/.codex/AGENTS.md; \
		printf '\n' >> codex/.codex/AGENTS.md; \
	done
	@echo "Generated codex/.codex/AGENTS.md from $$(ls $(MEMORIES)/*.md | wc -l) memory files"
	@python3 scripts/merge-codex-config.py "$(TARGET)/.codex/config.toml"
	@echo "Generated ~/.codex/config.toml from config.base.toml"
